apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx-deployment
  labels:
    app: simple-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - name: simple-nginx
        image: nginx
        resources:
          requests:
            memory: 300M
            cpu: 50m
        ports:
        - containerPort: 80
